# Generated by Django 5.0.6 on 2024-06-09 15:15

import django.core.validators
import file_uploads_in_drf.example.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackS3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(
                            access_key="minioadmin",
                            bucket_name="tracks",
                            default_acl="private",
                            endpoint_url="http://localhost:9000",
                            secret_key="minioadmin",
                            signature_version="s3v4",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="track",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    ),
                    file_uploads_in_drf.example.models.validate_file_size,
                ],
            ),
        ),
    ]
