---
version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2024-05-27T19-17-46Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address "0.0.0.0:9001"
    network_mode: host
    volumes:
      - .s3:/data
